### ISSUE TITLE
Webapps. . . . 

### ISSUE THREAD

**Issue by aaron-is-the-best2114** [phoenixbyrd/webapps#4]
@phoenixbyrd I am requesting permission to put Twister OS webapps on an app downloader called pi-apps.  I'm running Twister OS 2.0.0 and I got to thinking that it would be nice to have twister os webapps on a different OS for a little project I want to do.  This can be used for people who have SD cards that aren't large enough to hold version of Twister OS with these webapps, I have everything prepared like install and uninstall scripts for pi-apps.  I just need someones permission to put it on Pi-apps.  I ran into an issue where I used to have a Raspberry pi 3 with twister OS 2.0.0 install with these Twister OS webapps installed, and it also corrupted the 16 GB SD that was  in it as well, the only thing I had was a pi 2 and an 8 GB SD card.  so I really couldn't run a version of Twister OS with these webapps installed.  I really wanted these webapps on my Basic Raspberry pi OS because there's online games on Twister OS webapps and it doesn't take up much stoarge.  Yes you can download the zip file from this github page but I think it's just much easier to have it on pi-apps and to make everyone elses life easier.  Here is my github page with my version of Twister OS webapps https://github.com/aaron-is-the-best2114/Twister-OS-webapps and here is the Zip file with the install and uninstall scripts for pi-apps.  
[Twister-OS-Webapps.zip](https://github.com/phoenixbyrd/webapps/files/6743470/Twister-OS-Webapps.zip)

This is to have Twister OS webapps on any operating system that works on a raspberry pi.  I just need the okay to do it.

**Comment by phoenixbyrd** [comment]
No, I would rather it not be added to pi-apps. This was made specifically for Twister OS and I personally consider pi-apps to be malware. Twister OS is for the pi4, please upgrade for a better experience.

**Comment by Botspot** [comment]
> and I personally consider pi-apps to be malware.

Wow that's quite a statement.
Let's be reminded of the definition of malware:
![2021-07-10-135021_1366x768_scrot](https://user-images.githubusercontent.com/54716352/125173660-e8595280-e185-11eb-97c4-e0c1a799438e.png)
I may be forgetting, but I can't remember a single instance when Pi-Apps was specifically designed to disrupt, damage, or gain unauthorized access to a computer system.
Yes there have been a few times when an app caused problems or when Pi-Apps interfered with Box86 on TwisterOS, but to the best of my knowledge, 100% of those instances were genuine mistakes and should be considered bugs, not software attacks.
Any comments, @phoenixbyrd?
